@startuml
!include .\\Contracts\AreaContractGroup.puml
!include .\\Contracts\AreaNetVolume.puml
!include .\\Contracts\AreaPrice.puml
!include .\\Contracts\Auction.puml
!include .\\Contracts\AuctionMultiResolutionResponse.puml
!include .\\Contracts\Block.puml
!include .\\Contracts\BlockList.puml
!include .\\Contracts\BlockOrderPatchRequest.puml
!include .\\Contracts\CancelAllOrdersResponse.puml
!include .\\Contracts\Contract.puml
!include .\\Contracts\ContractNetVolume.puml
!include .\\Contracts\ContractPrice.puml
!include .\\Contracts\Currency.puml
!include .\\Contracts\CurrencyPrice.puml
!include .\\Contracts\Curve.puml
!include .\\Contracts\CurveOrder.puml
!include .\\Contracts\CurveOrderPatchRequest.puml
!include .\\Contracts\CurveOrderRequest.puml
!include .\\Contracts\CurvePoint.puml
!include .\\Contracts\Enums.puml
!include .\\Contracts\OrdersResponse.puml
!include .\\Contracts\OrderType.puml
!include .\\Contracts\Period.puml
!include .\\Contracts\Portfolio.puml
!include .\\Contracts\PortfolioArea.puml
!include .\\Contracts\PortfolioNetVolume.puml
!include .\\Contracts\PortfolioVolumesResponse.puml
!include .\\Contracts\PricesResponse.puml
!include .\\Contracts\ReasonabilityResultsInfo.puml
!include .\\Contracts\TradesSummary.puml
!include .\\Repositories\IAuctionRepository.puml
!include .\\Repositories\ICurveOrderRepository.puml
!include .\\Repositories\ITradesRepository.puml
!include .\\obj\Debug\net10.0\.NETCoreApp,Version=v10.0.AssemblyAttributes.puml
!include .\\obj\Debug\net10.0\3_Domain_layer.AssemblyInfo.puml
!include .\\obj\Debug\net10.0\3_Domain_layer.GlobalUsings.g.puml
!include .\\obj\Debug\net10.0\Domain.AssemblyInfo.puml
!include .\\obj\Debug\net10.0\Domain.GlobalUsings.g.puml
!include .\\obj\Debug\net10.0\Domain_layer.AssemblyInfo.puml
!include .\\obj\Debug\net10.0\Domain_layer.GlobalUsings.g.puml
@enduml
