@startuml
class AuctionMultiResolutionResponse {
    + Id : string <<get>> <<set>>
    + Name : string <<get>> <<set>>
    + State : AuctionStateType <<get>> <<set>>
    + CloseForBidding : DateTime <<get>> <<set>>
    + DeliveryStart : DateTime <<get>> <<set>>
    + DeliveryEnd : DateTime <<get>> <<set>>
    + AvailableOrderTypes : List<OrderType> <<get>> <<set>>
    + Currencies : List<Currency> <<get>> <<set>>
    + Contracts : List<AreaContractGroup> <<get>> <<set>>
    + Portfolios : List<Portfolio> <<get>> <<set>>
}
@enduml
