@startuml
enum OrderResultType {
    Curve= 0,
    Block= 1,
}
enum TradeSide {
    Buy= 0,
    Sell= 1,
}
enum OrderStateType {
    New= 0,
    Accepted= 1,
    Cancelled= 2,
    UserAccepted= 3,
    ResultsPublished= 4,
    None= 5,
}
enum AuctionStateType {
    Open= 0,
    Closed= 1,
    ResultsPublished= 2,
    Cancelled= 3,
}
enum PortfolioPermission {
    None= 0,
    READ= 1,
    WRITE= 2,
}
enum AuctionResultState {
    NotAvailable,
    PreliminaryResults,
    Final,
    InitialPrice,
}
@enduml
